version: '3.8'

services:
  apppayment:
    build:
      context: .
    command: bash start-dev.sh
    ports:
      - "8086:8086"
      - "5010:5005"
    environment:
      GRADLE_USER_HOME: /box
      SPRING_PROFILES_ACTIVE: dev
    volumes:
      - .:/payment
      - boxpayment:/box
    depends_on:
      - dbpayment
    networks:
      - ead-microservices-net
  dbpayment:
    image: postgres:14.5
    environment:
      POSTGRES_USER: ead-payment
      POSTGRES_PASSWORD: ead-payment
      POSTGRES_DB: ead-payment
    ports:
      - "5435:5432"
    networks:
      - ead-microservices-net
  boxpayment:
    image: busybox
    volumes:
      - /box
    networks:
      - ead-microservices-net
networks:
  ead-microservices-net:
    name: ead-microservices-net
    external: true
volumes:
  dbpayment:
  boxpayment: